// vitest.config.ts
import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: './src/test/setup.ts',
    exclude: ['**/node_modules/**', '**/dist/**', 'e2e/**'],
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        'src/lib/api.ts',    // axios singleton + interceptors — infrastructure code
        'src/test/**',       // test setup files
        '**/*.config.*',     // config files
        '**/*.d.ts',         // type declarations
        // Vendored shadcn/ui "base-nova" primitives generated by the shadcn CLI
        // (third-party component code, not our logic). See #76.
        'src/components/ui/{sidebar,sheet,dialog,command,dropdown-menu,breadcrumb,tooltip,separator,card,scroll-area,collapsible,sonner,select,switch,checkbox,tabs,textarea,input-group}.tsx',
        // recharts SVG wrappers — declarative chart config, no branching logic.
        'src/components/admin/charts/*.tsx',
        'src/hooks/use-mobile.ts',
      ],
      thresholds: {
        branches: 80,
        functions: 80,
        lines: 80,
        statements: 80,
      },
    },
  },
});
